# Generated by Django 5.1.6 on 2025-04-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanism',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
